# Generated by Django 5.1 on 2024-08-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flower",
            name="image",
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
