# Generated by Django 5.1.1 on 2024-09-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_post_author_post_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CareTip",
        ),
        migrations.DeleteModel(
            name="Flower",
        ),
    ]
